server:
  port: 8301
spring:
  application:
    name: borrow-service
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@replica1:8005/eureka,
                   http://root:123456@replica2:8006/eureka
feign:
  circuitbreaker:
    enabled: true
logging:
  level:
    com.test.service.UserService: debug
    com.test.service.BookService: debug
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' #暴露hystrix监控端点
service-url:
  user-service: http://user-service
  book-service: http://book-service

