server:
  port: 8601
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://gitee.com/YuanJianWei/springcloud-config.git
          username: YuanJianWei
          password: 13851176590++
          default-label: master
          clone-on-start: true #开启启动时直接从git获取配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@replica1:8005/eureka,
        http://root:123456@replica2:8006/eureka
